import { Post } from './post.model';

export const POSTS: Post[] = [
  new Post("Popular", "My friend’s cat just sits there and judges you.","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", 1),
  new Post("Random", "Guy from high school got the same tattoo as his dog.","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor.", 2),
  new Post("Popular", "First one to the wall wins.","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", 3),
  new Post("Popular", "The Andean Condor is absolutely enormous.","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ", 4),
  new Post("Popular", "What hobby screams rich people?","Country Club Memberships. I only know this because I worked at a country club in Columbus Ohio. It is a Pool, restaurant, and 300 acres of hiking trails. No golf course. I took a look at the member book, alongside the head server who has been there longer then I have been alive. She pointed out to a few names and stated such and such hasn't been here in x years or such and such has never been here but pays their dues. I asked her why would anyone be a member and never show up. She answered: Status. Apparently, the country club i worked at is a prestigious one as it has denied a handful of millionaires/billionaires. You have to pass a 12+ person board, and before any of that, you have to be recommended by a current member. Rich folks have a hobby of collecting country club memberships across the world.", 5),
  new Post("Popular", "Hawaiian parking hazard...","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.", 6)

];
